version: '3'
services:

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../:/var/www/
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=myapp
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - app-network
    command: sh -c "composer install && php artisan migrate:fresh && php-fpm"

  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app-network

  nginx:
    image: nginx:1.21.6-alpine
    volumes_from:
      - php
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
